[jenkins]
node2 ansible_host=13.203.227.25 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/dashking.pem

[application]
appserver ansible_host=52.66.51.210 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/dashking.pem